### ISSUE TITLE
Updates ?

### ISSUE THREAD

**Issue by UffeJakobsen** [UffeJakobsen/volman#1]
Hi,

volman is a really nice piece of work - but it could need some updates.

Do you plan to develop it further ?
Will you accept updates/pull requests ?
or should I do my own branch (and subsequence port) ?

/Uffe

**Comment by jmptbl** [comment]
Hi,

Thanks.  I don't plan to develop it further.  Perhaps you'd like to take 
it over?  I'm happy to relinquish the name/project if you'd like to 
continue from where I left off. :)

Thanks,
Aragon

**Comment by UffeJakobsen** [comment]
Hi,
Yes I'd like to take it over - if that is ok with you :-)

Kind regards Uffe

**Comment by jmptbl** [comment]
Ok, looks like Github needs you to delete your fork first.  I tried to 
transfer my volman now, but it failed.

https://help.github.com/articles/how-to-transfer-a-repository

**Comment by UffeJakobsen** [comment]
I've deleted my fork now

**Comment by jmptbl** [comment]
Transfer request sent.  Thanks for taking this over!!

**Comment by UffeJakobsen** [comment]
I'm the one to say thank you :-)
